# Lab 1 (Due @ by 11:59 pm via Canvas/Gradescope)


Due: Tuesday Sep 26 @ 11:59 PM EST

### Submission Instructions
Submit this `ipynb` file to Gradescope (this can also be done via the assignment on Canvas).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to gradescope.

### Group Work

You are encouraged to work in groups for this Lab, however each student should submit their own notebook file to Gradescope. While each Part of the Lab depends on previous parts, talking through the problem with your group should help speed up both understanding and arriving at a solution.

In [1]:
# you will use the below modules on this lab
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import requests
from datetime import datetime
import pandas as pd
from bs4 import BeautifulSoup

## Part 1: Web Scraping Warm-Up (20 points)

Build a `df_premier` which contains the names and stadiums of all the current English Premier League Teams based [on this website](https://www.premierleague.com/clubs):

    df_premier.head()
    
yields an output:

| name                   | stadium                 |
|------------------------|-------------------------|
| Arsenal                | Emirates Stadium        |
| Aston Villa            | Villa Park              |
| AFC Bournemouth        | Vitality Stadium        |
| Brentford              | Gtech Community Stadium |
| Brighton & Hove Albion | Amex Stadium            |

Make sure you: 
- use BeautifulSoup
- print the `.head()` of the data frame when you are finished

**Hint:** there should only be two `class_` values you need to accomplish this.

In [2]:
# getting the content of the page
url = 'https://www.premierleague.com/clubs'
response = requests.get(url).text
# response
soup = BeautifulSoup(response)
names_list = soup.find_all(class_="club-card__name")
names_list = [names_list[i].text for i in range(len(names_list))]
# names_list
stadiums_list = soup.find_all(class_="club-card__stadium")
stadiums_list = [stadiums_list[i].text for i in range(len(stadiums_list))]
# stadiums_list

In [3]:
dct_premier = {'name': [], 'stadium': []}
for n in names_list:
    dct_premier['name'].append(n)
    
for s in stadiums_list:
    dct_premier['stadium'].append(s)
        
# dct_premier
df_premier = pd.DataFrame.from_dict(dct_premier)
# df_premier.set_index('name') 
df_premier.head()

                     name                  stadium
0                 Arsenal         Emirates Stadium
1             Aston Villa               Villa Park
2             Bournemouth         Vitality Stadium
3               Brentford  Gtech Community Stadium
4  Brighton & Hove Albion             Amex Stadium

# Part 2: A Trickier Web Scraper

For this problem, we will (together) create a small data set scraped from [flightaware.com](https://flightaware.com/) which includes some details from the current flight schedule at Boston Logan Airport. You will build the first two parts of the data pipeline as functions (Parts 2.1 and 2.2) and then provide a detailed overview/description of the last two parts of the pipeline based on code I have written/provided (Parts 2.3 and 2.4). Please do not take these final two parts lightly!

## Part 2.1: The Scraper Function (20 points)

Complete the function `get_airport_html()` below (including docstring) which visits the url of a given US airport code and grabs the html. Visit [flightaware.com](https://flightaware.com/) and type in a few codes (e.g. BOS, JFK, LAX, RDU) and notice the pattern in the url so that you can pass any airport code to the function as a string. **Make sure to remove the `pass` statement when you are finished**. I have written the code you should run once the function is completed.

In [4]:
def get_airport_html(code):
    """ grabs html (using requests library) from flightaware.com with given code and returns it
        params: airport code (string)
        returns: corresponding html for given airport code
    """ 
    url = f"https://www.flightaware.com/live/airport/K{code}"
    html = requests.get(url).text
    return html

In [5]:
# when you are done the following code should be run
url_text = get_airport_html('LAX')
# url_text

## Part 2.2: The Soup Function (20 points)

Complete the function `get_airport_table_soup()` below (including docstring) which takes the html from the previous function and outputs one of four beautiful soup objects, depending on the board you are interested in as defined by the `'id'` attribute:

    - `id='arrivals-board'`
    - `id='departures-board'`
    - `id='enroute-board'`
    - `id='scheduled-board'`
    
The function should take two arguments: the html object from `get_airport_html()` and a string that specifies the `id` you are interested in (by default, the arrivals board).
    
**Make sure to remove the `pass` statement when you are finished.**

In [11]:
def get_airport_table_soup(html, board='arrivals-board'):
    """ outputs beautiful soup object based on given board id
        params: html from given website, board id from one of the 4 boards
        returns: corresponding soup object
    """
    soup = BeautifulSoup(html)
    return soup.find(id=board)

In [12]:
# when you are done the following code should be run (feel free to change the board if you wish)
board_choice = 'enroute-board'
my_board_soup = get_airport_table_soup(url_text, board_choice)
# my_board_soup

## Part 2.3: Cleaning The Board (20 points)

Below is the function `clean_board_df()`, which takes the soup object from the previous function and creates a data frame with the following columns:

    - `flight number`: the flight number
    - `aircraft type`: the type of aircraft
    - `airport name`: the name of the originating/destination airport (depending on type of board)
    - `airport code`: the letter code of the originating/destination airport
    - `departure time`: the time of the flight's departure
    - `arrival time`: the time of the flight's arrival

I have written the function and (given your function from Part 2.2 works) it should work. **DO NOT CHANGE ANYTHING IN THE BODY OF THE FUNCTION.**

**In a markdown cell** create a bullet point list where you explain each what each chunk of code does. Your bullet point list should have **FOUR** bullet points/explanations corresponding to the four chunks below the `# EXPLAIN THIS (number)` comments. You do not have to be super detailed, but you must accurately summarize the intention of each code chunk. **Talking to your neighbors/group about this is highly recommended.**

In [13]:
def clean_board_df(soup):    
    """ takes the soup of a board and cleans it, creating a data frame

    Args:
        soup (soup): the soup from get_airport_table_soup

    Returns:
        clean_board_df (data frame): a data frame with six columns corresponding to
            flight number
            aircraft type
            airport name
            airport code
            departure time
            arrival time
    """
    
    # EXPLAIN THIS (1)
    names = soup.find_all('span', attrs = {'title':True})
    flight_number = []
    aircraft_type = []
    airport_name = []
    for idx in range(0, len(names), 3):
        flight_number.append(names[idx].text)
        aircraft_type.append(names[idx+1].text)
        airport_name.append(names[idx+2].text)

    # EXPLAIN THIS (2)
    codes = soup.find_all(attrs = {'dir': 'ltr'})
    airport_code = []
    for idx in range(0, len(codes), 2):
        airport_code.append(codes[idx+1].text.replace("(", "").replace(")", ""))

    # EXPLAIN THIS (3)
    times = soup.find_all(class_='tz')
    departure_time = []
    arrival_time = []
    for idx in range(0, len(times), 2):
        dep_split_string = times[idx].previous_sibling.split('\xa0')
        arr_split_string = times[idx+1].previous_sibling.split('\xa0')
        
        if dep_split_string[0].endswith('a') == True:
            dep_datetime_str = dep_split_string[0][:-1] + ' AM'
            dep_datetime_time = datetime.strptime(dep_datetime_str, '%I:%M %p').time()
            departure_time.append(dep_datetime_time)
        else:
            dep_datetime_str = dep_split_string[0][:-1] + ' PM'
            dep_datetime_time = datetime.strptime(dep_datetime_str, '%I:%M %p').time()
            departure_time.append(dep_datetime_time)
        
        if arr_split_string[0].endswith('a') == True:
            arr_datetime_str = arr_split_string[0][:-1] + ' AM'
            arr_datetime_time = datetime.strptime(arr_datetime_str, '%I:%M %p').time()
            arrival_time.append(arr_datetime_time)
        else:
            arr_datetime_str = arr_split_string[0][:-1] + ' PM'
            arr_datetime_time = datetime.strptime(arr_datetime_str, '%I:%M %p').time()
            arrival_time.append(arr_datetime_time)

    # EXPLAIN THIS (4)
    clean_board_dict = {'flight number': flight_number,
                        'aircraft type': aircraft_type,
                        'airport name': airport_name,
                        'airport code': airport_code,
                        'departure time': departure_time,
                        'arrival time': arrival_time}
    clean_board_df = pd.DataFrame.from_dict(clean_board_dict)
    
    return clean_board_df
    
clean_df = clean_board_df(my_board_soup)
clean_df

,flight number,aircraft type,airport name,airport code,departure time,arrival time
0,EVA620,B77L,Taiwan Taoyuan Int'l,TPE,17:12:00,13:21:00
1,AAL1383,B738,Chicago O'Hare Intl,ORD,11:44:00,13:23:00
2,SKW3913,E75L,Sacramento Intl,SMF,12:21:00,13:23:00
3,EJA788,CL35,San Francisco Int'l,KSFO,12:00:00,13:24:00
4,CKK229,B77L,Shenzhen Bao'an Int'l,SZX,16:15:00,13:24:00
5,SKW3179,E75L,San Francisco Int'l,SFO,12:26:00,13:26:00
6,UBT71B,B789,London Gatwick,LGW,11:02:00,13:26:00
7,AAL1331,A21N,Dallas-Fort Worth Intl,DFW,12:51:00,13:29:00
8,SKW3904,E75L,Albuquerque Intl Sunport,ABQ,12:58:00,13:29:00
9,SKW3360,E75L,San Francisco Int'l,SFO,12:36:00,13:29:00
10,VIR7,A35K,London Heathrow,LHR,11:21:00,13:30:00
11,DAL473,B752,Boston Logan Intl,BOS,11:12:00,13:31:00
12,UAL2675,B39M,Houston Bush Int'ctl,IAH,12:33:00,13:31:00
13,SKW4883,E75L,Seattle-Tacoma Intl,SEA,11:16:00,13:33:00
14,DAL895,B763,Hartsfield-Jackson Intl,ATL,12:36:00,13:34:00
15,ASA1447,B738,Los Cabos Int'l,SJD,11:41:00,13:42:00
16,SWA580,B737,San Jose Int'l,SJC,12:45:00,13:43:00
17,SWA704,B737,Harry Reid Intl,LAS,12:53:00,13:44:00
18,AAL1987,B738,Chicago O'Hare Intl,ORD,12:14:00,13:50:00
19,VIV510,A320,Don Miguel Hidalgo y Costilla Int'l,GDL,11:55:00,13:50:00

Your answer in this cell:
- Chunk 1: extract all elements of page with the 'span' tag and where the 'title' attribute is true;
           create and populate flight_number, aircraft_type, and airport_name lists by looping over the 
           length of all extracged elements, and assuming the lists' information comes in the following
           order: flight number -> aircraft_type -> airport_name 
- Chunk 2: extract all elements of page with 'ltr' for the 'dir' attribute;
           create airport_code list and populate by looping over all elements while removing leading '(' s 
           and trailing ')' s
- Chunk 3: extract all elements of page with 'tz' class type; create and populate departure_time and
           arrival_time lists by looping over all the extracted elements and using the previous/next_sibling
           methods -> perform some string manipulations to determine whether the times are in the morning or at
           night, and use datetime.strptime method to strip the times for each time string;
           perform previous manipulations to both the departure and arrival times
- Chunk 4: initialize dict with all the names of the created lists (from previous chunks of code) as the dict
           keys, and the actual lists as the corresponding values; create df from previous dict and return it

## Part 2.4: Grabbing More Data (20 points)

Below (already written for you) is the function `get_aircraft_info()` which cycles through the different aircraft types in the data frame from the previous part and adds a column with a count of the number of aircrafts currently operating of that type. **DO NOT CHANGE ANYTHING IN THE BODY OF THE FUNCTION.**

**In a markdown cell** explain in why we were able to use `pd.read_html()` instead of `requests.get()` and comment on the values in the new column; is there something off about them?

**Hint:** you may want to take a look at an example url in your browser.

**Note:** I occasionally got an HTTPS error when running this; just wait a minute and try again, it should eventually work...

In [9]:
def get_aircraft_info(clean_df):
    """ takes a data frame of an aircraft board and adds a column with count of aircraft types

    Args:
        clean_df (data frame): the output of clean_board_df

    Returns:
        clean_df (data frame): the same data frame, but with an extra column
    """
 
    # get a list of aircraft types from the initial data frame
    aircraft_type = list(clean_df['aircraft type'])

    #initialize an empty list to count the number of each type
    num_type = []

    # loop through the different types
    for idx in range(len(aircraft_type)):

        # get the url for each type
        craft_url = f'https://flightaware.com/live/aircrafttype/{aircraft_type[idx]}'

        # grab the table from the url
        craft_tables = pd.read_html(craft_url)

        # add the info from the table to the list
        num_type.append(craft_tables[2].shape[0])

    # turn the list into a series and add it to the data frame
    clean_df['num type'] = pd.Series(num_type)

    # return the updated data frame
    return clean_df

final_df = get_aircraft_info(clean_df)

In [10]:
final_df

,flight number,aircraft type,airport name,airport code,departure time,arrival time,num type
0,EVA620,B77L,Taiwan Taoyuan Int'l,TPE,17:12:00,13:21:00,20
1,AAL1383,B738,Chicago O'Hare Intl,ORD,11:44:00,13:23:00,20
2,SKW3913,E75L,Sacramento Intl,SMF,12:21:00,13:23:00,20
3,EJA788,CL35,San Francisco Int'l,KSFO,12:00:00,13:24:00,1
4,CKK229,B77L,Shenzhen Bao'an Int'l,SZX,16:15:00,13:24:00,20
5,SKW3179,E75L,San Francisco Int'l,SFO,12:26:00,13:26:00,20
6,UBT71B,B789,London Gatwick,LGW,11:02:00,13:26:00,20
7,AAL1331,A21N,Dallas-Fort Worth Intl,DFW,12:51:00,13:29:00,20
8,SKW3904,E75L,Albuquerque Intl Sunport,ABQ,12:58:00,13:29:00,20
9,SKW3360,E75L,San Francisco Int'l,SFO,12:36:00,13:29:00,20
10,VIR7,A35K,London Heathrow,LHR,11:21:00,13:30:00,20
11,DAL473,B752,Boston Logan Intl,BOS,11:12:00,13:31:00,20
12,UAL2675,B39M,Houston Bush Int'ctl,IAH,12:33:00,13:31:00,20
13,SKW4883,E75L,Seattle-Tacoma Intl,SEA,11:16:00,13:33:00,20
14,DAL895,B763,Hartsfield-Jackson Intl,ATL,12:36:00,13:34:00,20
15,ASA1447,B738,Los Cabos Int'l,SJD,11:41:00,13:42:00,20
16,SWA580,B737,San Jose Int'l,SJC,12:45:00,13:43:00,20
17,SWA704,B737,Harry Reid Intl,LAS,12:53:00,13:44:00,20
18,AAL1987,B738,Chicago O'Hare Intl,ORD,12:14:00,13:50:00,20
19,VIV510,A320,Don Miguel Hidalgo y Costilla Int'l,GDL,11:55:00,13:50:00,20

We were able to use pd.read_html() instead of using request.get() and Beautiful Soup because the data
is tabulated nicely for us, and so this case of web scraping falls under the easiest scenario :)
Looking at: https://www.flightaware.com/live/airport/KLAX, I can tell that the num type column has the same value
for all flight numbers except for the CL35 aircraft type. I find it mysterious that the number of aircrafts currently
operating is the same (basically), and as of now, I'm not sure how to interpret this fact.